language: python
python:
  - "3.7"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - mkdir data
  - python train_model.py
  - pytest app
